apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluegreen
bases:
- ../../../../lib/tester
- ../../../../lib/debug
- ../../../../lib/bluegreen
- ../../../../lib/podinfo

#patchesStrategicMerge:
#  - webhooks-patch.yaml
