apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canary
bases:
- ../../../../lib/tester
- ../../../../lib/debug
- ../../../../lib/canary
- ../../../../lib/podinfo

#patchesStrategicMerge:
#  - webhooks-patch.yaml
